# Gearbot Animal API Azure CI/CD
trigger:
- master

variables:
- group: DiscordWebhook-DeploymentMonitoring

stages:
- stage: Tests

  jobs:
  - job: cargo_tests
    displayName: Cargo Test

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - template: ci/installrust.yml

    - script: cargo test
      displayName: Cargo test

  - job: check_clippy
    displayName: Clippy
    dependsOn: cargo_tests

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - template: ci/installrust.yml

    - script: rustup component add clippy
      displayName: Install Clippy

    - script: cargo clippy --all -- -D clippy::all
      displayName: Clippy Check
    
  - job: cargo_check
    displayName: Cargo Check
    dependsOn: cargo_tests
    
    strategy:
      matrix:
        Windows Stable:
          imageName: 'vs2017-win2016'
          rustup_toolchain: stable
        Windows Nightly:
          imageName: 'vs2017-win2016'
          rustup_toolchain: nightly

        Linux Stable:
          imageName: 'ubuntu-latest'
          rustup_toolchain: stable
        Linux Nightly:
          imageName: 'ubuntu-latest'
          rustup_toolchain: nightly
      
    pool:
      vmImage: $(imageName)

    steps:
    - template: ci/installrust.yml
      parameters:
        rust_toolchain: $(rustup_toolchain)

    - script: cargo check --all --bins
      displayName: Cargo Check


- stage: Build
  dependsOn: Tests
  condition: succeeded()

  jobs:
  - job: build_binary
    displayName: Build Binary

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - template: ci/installrust.yml

    - script: cargo rustc --release --bin animal_api -- -C lto -C link-args=-s
      condition: ne(variables['build.reason'], 'PullRequest')
      displayName: Startup release compile

    - script: cargo build
      condition: eq(variables['build.reason'], 'PullRequest')
      displayName: Startup pull request compile

    # Artifacts are needed for the startup test, even on PRs
    - task: PublishPipelineArtifact@0
      displayName: Publish deploy binary
      condition: and(succeeded(),  ne(variables['build.reason'], 'PullRequest'))
      inputs:
        artifactName: 'animal_api'
        targetPath: './target/release/animal_api'

    # Artifacts are needed for the startup test, even on PRs
    - task: PublishPipelineArtifact@0
      displayName: Publish debug binary
      condition: and(succeeded(),  eq(variables['build.reason'], 'PullRequest'))
      inputs:
        artifactName: 'animal_api'
        targetPath: './target/debug/animal_api'

  - job: startup_test
    displayName: Startup Test
    dependsOn: build_binary
    condition: succeeded()

    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - script: cp default_config.toml config.toml
        displayName: Create config

      - task: DownloadPipelineArtifact@1
        displayName: Download Binary
        inputs:
          buildType: 'current'
          artifactName: 'animal_api'
          targetPath: '$(System.DefaultWorkingDirectory)'

      - script: |
          chmod +x ./animal_api
          RESULTS=`./animal_api & last_pid=$!; sleep 5; kill -s TERM $last_pid`
          echo "##vso[task.setvariable variable=startupResult;]$RESULTS"
        displayName: Startup Panic Test
        
      - script: 'echo $(startupResult); exit 1'
        displayName: Startup failure
        condition: contains(variables['startupResult'], 'thread')

      - script: rm -rf config.toml ./example_facts ./logs
        displayName: Clean repo contents

      - task: PublishPipelineArtifact@1
        displayName: Generate deploy files
        condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
        inputs:
          targetPath: '$(System.DefaultWorkingDirectory)'
          artifact: 'DeployFiles'


- stage: Deploy
  dependsOn: Build
  condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))

  jobs:
    - deployment: deploy_to_vm
      displayName: Deploy to VM
      environment: Production

      pool:
        vmImage: 'ubuntu-latest'

      strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadPipelineArtifact@1
              displayName: Download deploy files
              inputs:
                buildType: 'current'
                artifactName: 'DeployFiles'
                targetPath: '$(System.DefaultWorkingDirectory)'
            
            - task: SSH@0
              displayName: Stop Service
              inputs:
                sshEndpoint: 'GearBox'
                runOptions: 'commands'
                commands: 'sudo systemctl stop animalapi.service'
            
            - task: CopyFilesOverSSH@0
              displayName: Copy deployment to VM
              inputs:
                sshEndpoint: 'GearBox'
                contents: '**'
                targetFolder: './animal_api/'
                failOnEmptySource: true

            - task: SSH@0
              displayName: Start Service
              inputs:
                sshEndpoint: 'GearBox'
                runOptions: 'commands'
                commands: 'chmod +x ./animal_api/animal_api; sudo systemctl start animalapi.service'
            
            # Notify admins via Discord of the deployment
            - template: ci/discordnotify.yml
