[package]
name = "gearbot_cat_api"
version = "0.1.0"
authors = ["BlackHoleFox <blackholefoxdev@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.0-alpha.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"
rand = "0.6"